CycleHire/CycleHire/Controllers/ListingController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CycleHire.Persistence.UnitOfWork;
using CycleHire.Core.ViewModels.ListingViewModels;
using AutoMapper;
using CycleHire.Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using CycleHire.Core.ViewModels;
using System.Collections.Generic;
using CycleHire.Services;
using CycleHire.Core.ViewModels.ReviewViewModels;

namespace CycleHire.Controllers
{
    public class ListingController : Controller
    {
        private readonly IImageUploader _imageUploader;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public ListingController(IImageUploader imageUploader, IUnitOfWork unitOfWork, IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            _imageUploader = imageUploader;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }
        // GET: Listing
        public ActionResult Index()
        {
            return View();
        }

        // GET: Listing/Details/5
        public async Task<ActionResult> Details(Guid id)
        {

            var listing = await _unitOfWork.Listings.GetByIdWithImagesAndAccessories(id);

            if (listing == null)
            {
                return NotFound();
            }

            var reviews = await _unitOfWork.Reviews.GetByListingId(id);

            var model = _mapper.Map<ListingDetailsViewModel>(listing);

            model.Review = new HostReviewSummaryViewModel(reviews);

            return View(model);
        }

        [Authorize]
        // GET: Listing/Create
        public async Task<ActionResult> Create()
        {
            var model = new ListingForm
            {
                Accessories = _mapper.Map<List<KeyValueViewModel>>
                    (await _unitOfWork.Accessories.GetAllAsync())
            };

            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ListingForm model)
        {
            if (!ModelState.IsValid)
            {
                model.Accessories = _mapper.Map<List<KeyValueViewModel>>
                    (await _unitOfWork.Accessories.GetAllAsync());

                model.Availability.PopulateDaysOfWeek();

                return View(model);
            }

            var userId = _userManager.GetUserId(HttpContext.User);

            var images = _mapper.Map<List<ListingImage>>
                (await _imageUploader.UploadImagesAsync(model.UploadedImages));

            var listing = _mapper.Map<Listing>(model);

            listing.UserId = userId;
            listing.Images = images;

            await _unitOfWork.Listings.AddAsync(listing);

            _unitOfWork.Complete();

            _unitOfWork.Listings.SetSpatialLocation(listing.Latitude, listing.Longitude, listing.Id);

            return RedirectToAction("Details", new { id = listing.Id });
        }

        // GET: Listing/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Listing/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Listing/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Listing/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CycleHire/CycleHire/Controllers/ReviewController.cs
using Microsoft.AspNetCore.Mvc;
using CycleHire.Persistence.UnitOfWork;
using AutoMapper;
using Microsoft.AspNetCore.Identity;
using CycleHire.Core.Models;
using System.Threading.Tasks;
using System;
using CycleHire.Core.ViewModels.ReviewViewModels;
using Microsoft.AspNetCore.Authorization;

namespace CycleHire.Controllers
{
    [Authorize]
    public class ReviewController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public ReviewController(IUnitOfWork unitOfWork, IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }

        public async Task<IActionResult> Pending()
        {
            var userId = _userManager.GetUserId(User);

            var model = new ReviewIndexViewModel();

            if (User.IsInRole("Host"))
            {
                model.UserType = UserType.Host;
                model.PendingReviewsAboutTenant = await _unitOfWork.Reviews
                    .GetPendingReviewsAboutTenant(userId);
            }

            model.PendingReviewsAboutHost = await _unitOfWork.Reviews
                .GetPendingReviewsAboutHost(userId);

            return View(model);
        }

        public async Task<IActionResult> Created()
        {
            var userId = _userManager.GetUserId(User);

            var model = new ReviewIndexViewModel();

            if (User.IsInRole("Host"))
            {
                model.UserType = UserType.Host;

                model.ReviewsAboutTenants = await _unitOfWork.Reviews
                    .GetTenantReviewsByUserId(userId);
            }

            model.ReviewsAboutHosts = await _unitOfWork.Reviews
                .GetHostReviewsByUserId(userId);

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Host(Guid id)
        {
            var booking = await _unitOfWork.Bookings.GetById(id);

            var userId = _userManager.GetUserId(User);

            var isUser = IsTenantOfBooking(booking, userId);

            if (!isUser) { return Forbid(); }

            var model = new HostReviewViewModel
            {
                BookingId = booking.Id,
                BookingTo = booking.To
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Host(HostReviewViewModel model)
        {
            var booking = await _unitOfWork.Bookings.GetById(model.BookingId);

            if (!ModelState.IsValid)
            {
                model.BookingId = booking.Id;
                model.BookingTo = booking.To;
                return View(model);
            }

            var userId = _userManager.GetUserId(User);

            if (!IsTenantOfBooking(booking, userId)) { return Forbid(); }

            var review = _mapper.Map<HostReview>(model);
            review.UserId = userId;
            review.ListingId = booking.ListingId;

            _unitOfWork.Reviews.AddHostReview(review);
            _unitOfWork.Complete();

            return RedirectToAction("Created");
        }

        [HttpGet]
        public async Task<IActionResult> Tenant(Guid id)
        {
            var booking = await _unitOfWork.Bookings.GetById(id);

            var userId = _userManager.GetUserId(User);

            if (!IsHostOfBooking(booking, userId)) { return Forbid(); }

            var model = new TenantReviewViewModel
            {
                BookingId = booking.Id
            };

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Tenant(TenantReviewViewModel model)
        {
            var booking = await _unitOfWork.Bookings.GetById(model.BookingId);

            if (!ModelState.IsValid)
            {
                model.BookingId = booking.Id;
                model.BookingTo = booking.To;
                return View(model);
            }

            var userId = _userManager.GetUserId(User);

            if (!IsHostOfBooking(booking, userId)) { return Forbid(); }

            var review = _mapper.Map<TenantReview>(model);
            review.UserId = userId;
            review.ListingId = booking.ListingId;

            _unitOfWork.Reviews.AddTenantReview(review);
            _unitOfWork.Complete();

            return RedirectToAction("Created");
        }


        public bool IsHostOfBooking(Booking booking, string userId)
        {
            return booking.OwnerId == userId;
        }

        public bool IsTenantOfBooking(Booking booking, string userId)
        {
            return booking.UserId == userId;
        }
    }
}

CycleHire/CycleHire/Controllers/RouteController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace CycleHire.Controllers
{
    [Authorize]
    public class RouteController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

CycleHire/CycleHire/Views/Shared/_ApproveBookingModal.cshtml
@model Booking
<div class="ui modal" id="accept-booking-@Model.Id">
    <div class="header">
        Approve @Model.User.FullName() Booking Request
    </div>
    <div class="content">
        <div class="description">
            <p>Once you accept the booking request @Model.User.FullName() will be charged. You will recieve @Model.SubTotal.ToString("C") in a few days.</p>
            <p>I am able to rent out my bike out with all included accessories included in the listing from <b>@Model.From.ToString("D")</b> to <b>@Model.To.ToString("D") (@Model.DurationInDays days)</b>  ?</p>
        </div>
    </div>
    <div class="actions">

        <form asp-controller="Booking" method="post" asp-action="Approve" asp-route-id="@Model.Id">
            <div class="ui cancel button">Cancel</div>

            <input type="submit" value="Approve" class="ui primary button button" />
        </form>
    </div>
</div>

CycleHire/CycleHire/Views/Shared/_DeclineBookingModal.cshtml
@model CycleHire.Core.ViewModels.HostViewModels.HostDeclineViewModel
<div class="ui modal" id="decline-booking-@Model.BookingId">
    <div class="header">
        Decline @Model.TenantName Booking Request
    </div>
    <div class="content">
        <div class="description">
            <h3>Are you sure you want to decline @Model.TenantName booking request ?</h3>
            <form class="ui form" method="post" id="decline-form">
                @Html.HiddenFor(m => m.BookingId)
                <div class="field">
                    <label asp-for="Message">Message to @Model.TenantName (Optional)</label>
                    <textarea asp-for="Message"></textarea>
                </div>
            </form>
        </div>
    </div>
    <div class="actions">
        <div class="ui button">
            Cancel
        </div>
        <input type="submit" value="Decline" class="ui red button" form="decline-form" asp-controller="Booking" asp-action="Decline" asp-route-id="@Model.BookingId">
    </div>
</div>

CycleHire/CycleHire/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@using CycleHire.Core.ViewModels

@inject SignInManager<ApplicationUser> SignInManager
<!DOCTYPE html>
<html>
<head>
    <!-- Standard Meta -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/semantic/dist/semantic.min.css" />
    <environment include="Development">
        <link rel="stylesheet" href="~/lib/owl.carousel/dist/assets/owl.carousel.min.css" />
        <link rel="stylesheet" href="~/lib/owl.carousel/dist/assets/owl.theme.green.min.css" />
        <link rel="stylesheet" href="~/lib/pickadate/lib/compressed/themes/default.css" />
        <link rel="stylesheet" href="~/lib/pickadate/lib/compressed/themes/default.date.css" />
        <link rel="stylesheet" href="~/lib/intl-tel-input/build/css/intlTelInput.css">
        <link rel="stylesheet" href="~/lib/fullcalendar/dist/fullcalendar.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/lib/owl.carousel/dist/assets/owl.carousel.min.css" />
        <link rel="stylesheet" href="~/lib/owl.carousel/dist/assets/owl.theme.green.min.css" />
        <link rel="stylesheet" href="~/lib/pickadate/lib/compressed/themes/default.css" />
        <link rel="stylesheet" href="~/lib/pickadate/lib/compressed/themes/default.date.css" />
        <link rel="stylesheet" href="~/lib/intl-tel-input/build/css/intlTelInput.css">
        <link rel="stylesheet" href="~/lib/fullcalendar/dist/fullcalendar.min.css" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
    </environment>

    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
    </environment>
</head>
<body>
    <style>
        .ui.sidebar {
            overflow: visible !important;
        }
    </style>

    <div class="ui left vertical sidebar menu" id="left-menu">
        @if (SignInManager.IsSignedIn(User))
        {

            @if (User.IsInRole("Host"))
            {
                <a class="item" asp-controller="Host" asp-action="Index" is-active-route on-controller="Host" on-action="Index">
                    Dashboard
                </a>

                <div class="ui dropdown item">
                    <i class="dropdown icon"></i>
                    Listings
                    <div class="menu">
                        <a class="item" asp-controller="Host" asp-action="Listings" is-active-route on-controller="Host" on-action="Listings">
                            <i class="eye icon"></i> View
                        </a>
                        <a class="item" asp-controller="Listing" asp-action="Create" is-active-route on-controller="Listing" on-action="Create">
                            <i class="plus icon"></i> Create
                        </a>
                    </div>
                </div>
                <a class="item" asp-controller="Host" asp-action="Bookings" is-active-route on-controller="Host" on-action="Bookings">
                    Bookings
                </a>
            }

            <div class="ui dropdown item">
                <i class="dropdown icon"></i>
                Reviews
                <div class="menu">
                    <a class="item" asp-controller="Review" asp-action="Pending"><i class="plus icon"></i>Pending</a>
                    <a class="item" asp-controller="Review" asp-action="Created"><i class="pencil alternate icon"></i> Created</a>
                </div>
            </div>

            <a class="item" asp-controller="Booking" asp-action="Index" is-active-route on-controller="Booking" on-action="Index">
                My Bookings
            </a>
            <a class="item" asp-controller="Route" asp-action="Index" is-active-route on-controller="Route" on-action="Index">
                Route Planner
            </a>
        }

        <a class="item" asp-controller="Home" asp-action="About" is-active-route on-controller="Home" on-action="About">
            About
        </a>

        <a class="item" asp-controller="Home" asp-action="Contact" is-active-route on-controller="Home" on-action="Contact">
            Contact
        </a>
    </div>

    <div class="pusher">
        <div class="ui menu" id="top-menu">
            <a class="item mobile-button">
                <i class="content icon"></i>
            </a>
            <a asp-controller="Home" asp-action="Index" class="item"><i class="bicycle icon"></i></a>
            <div class="right menu">
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
        <div class="ui container">
            @RenderBody()
        </div>
    </div>

    <script>
        $(document).ready(function () {
            $('#left-menu').sidebar({
                transition: 'overlay'
            });

            $('#left-menu').sidebar('attach events', '.mobile-button');

            $('.ui.dropdown').dropdown();

            $('#js-profile').dropdown();

        })
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCVd95-clSTT6S4IUOlZnecChPsDksQNj0&libraries=places,drawing,geometry"></script>


    <environment include="Development">
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="~/lib/semantic/dist/semantic.min.js"></script>
        <script src="~/lib/owl.carousel/dist/owl.carousel.min.js"></script>
        <script src="~/lib/pickadate/lib/compressed/picker.js"></script>
        <script src="~/lib/pickadate/lib/compressed/picker.date.js"></script>
        <script src="~/lib/intl-tel-input/build/js/intlTelInput.js"></script>
        <script src="~/lib/intl-tel-input/build/js/utils.js"></script>
        <script src="~/lib/fullcalendar/dist/fullcalendar.min.js"></script>

        <script src="~/js/app/shared/utilities.js"></script>
        <script src="~/js/app/services/calendarService.js"></script>
        <script src="~/js/app/services/routePlannerService.js"></script>

        <script src="~/js/app/controllers/calendarController.js"></script>
        <script src="~/js/app/controllers/fullCalendarController.js"></script>
        <script src="~/js/app/controllers/listingController.js"></script>
        <script src="~/js/app/controllers/googleMapsController.js"></script>
        <script src="~/js/app/controllers/routePlannerController.js"></script>


        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="~/lib/moment/min/moment.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/semantic-ui/2.2.2/semantic.min.js"
                asp-fallback-src="~/lib/semantic/dist/js/semantic.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.site">
        </script>
        <script src="~/lib/owl.carousel/dist/owl.carousel.min.js"></script>
        <script src="~/lib/pickadate/lib/compressed/picker.js"></script>
        <script src="~/lib/pickadate/lib/compressed/picker.date.js"></script>
        <script src="~/lib/intl-tel-input/build/js/intlTelInput.min.js"></script>
        <script src="~/lib/intl-tel-input/build/js/utils.js"></script>
        <script src="~/lib/fullcalendar/dist/fullcalendar.min.js"></script>

        <script src="~/js/app/shared/utilities.js"></script>
        <script src="~/js/app/services/calendarService.js"></script>
        <script src="~/js/app/services/routePlannerService.js"></script>

        <script src="~/js/app/controllers/calendarController.js"></script>
        <script src="~/js/app/controllers/fullCalendarController.js"></script>
        <script src="~/js/app/controllers/listingController.js"></script>
        <script src="~/js/app/controllers/googleMapsController.js"></script>
        <script src="~/js/app/controllers/routePlannerController.js"></script>

        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

CycleHire/CycleHire/Views/Shared/_NoItemsPartial.cshtml
@model NoItemsViewModel
<h2 class="ui icon header center aligned">
    <i class="@Model.Icon icon"></i>
    <div class="content">
        @Model.Heading
        <div class="sub header">@Model.Description</div>
    </div>
</h2>