CycleHire/CycleHire/Controllers/ListingController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using CycleHire.Persistence.UnitOfWork;
using CycleHire.Core.ViewModels.ListingViewModels;
using AutoMapper;
using CycleHire.Core.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using CycleHire.Core.ViewModels;
using System.Collections.Generic;
using CycleHire.Services;
using CycleHire.Core.ViewModels.ReviewViewModels;

namespace CycleHire.Controllers
{
    public class ListingController : Controller
    {
        private readonly IImageUploader _imageUploader;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public ListingController(IImageUploader imageUploader, IUnitOfWork unitOfWork, IMapper mapper,
            UserManager<ApplicationUser> userManager)
        {
            _imageUploader = imageUploader;
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
        }
        // GET: Listing
        public ActionResult Index()
        {
            return View();
        }

        // GET: Listing/Details/5
        public async Task<ActionResult> Details(Guid id)
        {

            var listing = await _unitOfWork.Listings.GetByIdWithImagesAndAccessories(id);

            if (listing == null)
            {
                return NotFound();
            }

            var reviews = await _unitOfWork.Reviews.GetByListingId(id);

            var model = _mapper.Map<ListingDetailsViewModel>(listing);

            model.Review = new HostReviewSummaryViewModel(reviews);

            return View(model);
        }

        [Authorize]
        // GET: Listing/Create
        public async Task<ActionResult> Create()
        {
            var model = new ListingForm
            {
                Accessories = _mapper.Map<List<KeyValueViewModel>>
                    (await _unitOfWork.Accessories.GetAllAsync())
            };

            return View(model);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ListingForm model)
        {
            if (!ModelState.IsValid)
            {
                model.Accessories = _mapper.Map<List<KeyValueViewModel>>
                    (await _unitOfWork.Accessories.GetAllAsync());

                model.Availability.PopulateDaysOfWeek();

                return View(model);
            }

            var userId = _userManager.GetUserId(HttpContext.User);

            var images = _mapper.Map<List<ListingImage>>
                (await _imageUploader.UploadImagesAsync(model.UploadedImages));

            var listing = _mapper.Map<Listing>(model);

            listing.UserId = userId;
            listing.Images = images;

            await _unitOfWork.Listings.AddAsync(listing);

            _unitOfWork.Complete();

            _unitOfWork.Listings.SetSpatialLocation(listing.Latitude, listing.Longitude, listing.Id);

            return RedirectToAction("Details", new { id = listing.Id });
        }

        // GET: Listing/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Listing/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Listing/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Listing/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

CycleHire/CycleHire/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using AutoMapper;
using CycleHire.Services;
using CycleHire.Persistence.UnitOfWork;
using CycleHire.Core.Models;
using CycleHire.Core.ViewModels.ProfileViewModels;
using Microsoft.AspNetCore.Http;
using CycleHire.Core.ViewModels;
using CycleHire.Core.ViewModels.ManageViewModels;

namespace CycleHire.Controllers
{
    public class ProfileController : Controller
    {
        private readonly IImageUploader _imageUploader;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public ProfileController(IUnitOfWork unitOfWork, IMapper mapper,
            IImageUploader imageUploader, UserManager<ApplicationUser> userManager)
        {
            _unitOfWork = unitOfWork;
            _mapper = mapper;
            _userManager = userManager;
            _imageUploader = imageUploader;
        }
        public async Task<IActionResult> Index(string id)
        {
            var user = await _userManager.FindByIdAsync(id);

            if (user == null) { return View(user); }

            user.Listings = await _unitOfWork.Listings.GetByUserIdWithImages(id);

            return View(user);
        }

        [HttpPost]
        public async Task<IActionResult> AddImage(IndexViewModel model)
        {
            if (model?.UploadImageModel?.Image == null)
            {
                return RedirectToAction("Index", "Manage");
            }

            var user = await _userManager.GetUserAsync(User);

            var imageId = await _imageUploader
                .UploadImageAsync(model.UploadImageModel.Image);

            user.ProfileImageId = imageId;

            await _userManager.UpdateAsync(user);

            return RedirectToAction("Index", "Manage");
        }
    }
}

CycleHire/CycleHire/Views/Listing/Create.cshtml
@model CycleHire.Core.ViewModels.ListingViewModels.ListingForm
@{
    ViewData["Title"] = "Create Listing";
}

<form asp-controller="Listing" asp-action="Create" enctype="multipart/form-data" class="ui form" method="post">
    <div class="field">
        <label asp-for="Title"></label>
        <input asp-for="Title" />
        <span asp-validation-for="Title" class="red-text"></span>
    </div>
    <div class="field">
        <label asp-for="Description"></label>
        <textarea asp-for="Description" class="data"></textarea>
        <span asp-validation-for="Description" class="red-text"></span>
    </div>

    <div class="field">
        <label asp-for="Accessories"></label>
        <select class="ui fluid dropdown multi-select multiple" asp-for="IncludedAccessories" asp-items="@(new SelectList(Model.Accessories,"Id","Name"))"></select>
        <span asp-validation-for="Accessories" class="red-text"></span>
    </div>

    <div class="field">
        <label asp-for="Price"></label>
        <input asp-for="Price" type="number" min="1" step="any" max="2500" value="1" />
        <span asp-validation-for="Price" class="red-text"></span>
    </div>

    <div id="js-location">
        <div class="field">
            <label asp-for="Address"></label>
            <input id="js-location-prediction" asp-for="Address" type="text" />
            <span asp-validation-for="Address" class="red-text"></span>
            <span asp-validation-for="Latitude" class="red-text"></span>
            <span asp-validation-for="Longitude" class="red-text"></span>
        </div>

        <input id="js-latitude" asp-for="Latitude" type="hidden" />
        <input id="js-longitude" asp-for="Longitude" type="hidden" />
    </div>

    <div class="field">
        <label asp-for="Availability.DayOfWeek"></label>
        <select class="ui fluid dropdown multi-select multiple" asp-for="Availability.SelectedDayOfWeek" asp-items="@(new SelectList(Model.Availability.DayOfWeek))"></select>
        <span asp-validation-for="Availability.SelectedDayOfWeek" class="red-text"></span>
    </div>
    <div class="field">
        <label asp-for="UploadedImages"></label>
        <input asp-for="UploadedImages" type="file" accept="image/*" multiple />
        <span asp-validation-for="UploadedImages" class="red-text"></span>
    </div>

    <button type="submit" class="ui primary submit button" id="submitButton">Submit</button>
</form>

@section Scripts {
    <script>

        $('.multi-select').dropdown();

        $(document).ready(function () {

            ListingController.initialize("#js-location")
            //Dropzone.autoDiscover = false;

            //Dropzone.options.myAwesomeDropzone = {
            //    autoProcessQueue: false,
            //    uploadMultiple: true,
            //    parallelUploads: 100,
            //    maxFilesize: 10, // 20MB max size
            //    maxFiles: 6,
            //    acceptedFiles: "image/*",
            //    addRemoveLinks: true,
            //    init: function () {
            //        var myDropzone = this;
            //        $("#submitButton").click(function (e) {
            //            // Make sure that the form isn't actually being sent.
            //            e.preventDefault();
            //            e.stopPropagation();
            //            myDropzone.processQueue();
            //        });
            //    }
            //};
        });
    </script>
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CycleHire/CycleHire/Views/Listing/Details.cshtml
@model CycleHire.Core.ViewModels.ListingViewModels.ListingDetailsViewModel
@inject IImageUploader images

@{
    ViewData["Title"] = "Listing Details";
}
<div class="ui items">
    <div class="item">
        <div class="content">
            <div class="header">@Model.Title</div>
        </div>
    </div>
</div>
<div class="ui stackable grid">
    <div class="ten wide column">
        <div class="owl-carousel owl-theme">
            @foreach (string id in Model.Images)
            {
                <img class="ui rounded image" src="@images.GetBikeImageById(id,490,690)" al alt="Uploaded by " + @Model.User.Firstname />
            }
        </div>
    </div>

    <div class="six wide column">
        <div class="ui fluid card">
            <div class="content">
                <div class="right floated meta">@Model.Created.DurationInDays()</div>
                <img class="ui avatar image" src="@images.GetProfileImageById(Model.User.ProfileImageId,30,30)">
                <a asp-controller="Profile" asp-action="Index" asp-route-id="@Model.User.Id">@Model.User.GetFullname()</a>
            </div>
            <div class="content">
                <div class="header">
                    @Html.DisplayFor(m => m.Price)
                </div>

                <div class="meta">per day</div>

                <div class="description">
                    <div class="keep-formatting" style="margin-bottom:0.5em">@Model.Description</div>

                    @if (Model.Accessories.Count > 0)
                    {
                        <p class="meta">Included Accessories</p>
                    }
                    @foreach (var accessory in Model.Accessories)
                    {
                        <p><i class="check square icon"></i>@accessory.Name</p>
                    }
                </div>
            </div>
        </div>

        <div class="ui fluid card">
            <div class="ui segment">
                <form asp-controller="Booking" asp-action="Create" method="get">
                    <div class="ui form js-calendar" data-listing-id="@Model.Id">
                        <div class="two fields">
                            @Html.HiddenFor(f => f.Id)
                            <div class="field">
                                <label asp-for="From"></label>
                                <input asp-for="From" class="datepicker" id="js-from" placeholder="From" data-listing-id="@Model.Id">
                            </div>
                            <div class="field">
                                <label asp-for="To"></label>
                                <input asp-for="To" class="datepicker" id="js-to" placeholder="To" data-listing-id="@Model.Id">
                            </div>
                        </div>
                        <div>
                            <div id="js-success-info">
                                <p id="js-total-days"></p>
                                <p id="js-total-price" data-price="@Model.Price"></p>
                            </div>
                            <p id="js-error"></p>
                            <button type="submit" class="ui fluid submit primary button" disabled id="js-button">Book</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<h2 class="ui header">
    <i class="certificate icon"></i>
    <div class="content">
        @(Model.Review.Reviews.Count() > 0 ? "Reviews" : "No Reviews")
    </div>
</h2>

@if (Model.Review.Reviews.Count() > 0)
{
    <div class="ui form">
        <div class="four fields">
            <div class="field">
                <label>Communication</label>
                <span class="ui massive star rating" data-rating="@Model.Review.AggreatedReview.ResponseAndCommunication" data-max-rating="5"></span>
            </div>
            <div class="field">
                <label>Accuracy</label>
                <span class="ui massive star rating" data-rating="@Model.Review.AggreatedReview.AccuracyOfListing" data-max-rating="5"></span>
            </div>
            <div class="field">
                <label>Value</label>
                <span class="ui massive star rating" data-rating="@Model.Review.AggreatedReview.Value" data-max-rating="5"></span>
            </div>
            <div class="field">
                <label>Location</label>
                <span class="ui massive star rating" data-rating="@Model.Review.AggreatedReview.Location" data-max-rating="5"></span>
            </div>
        </div>
    </div>

    <div class="ui divided items">
        @foreach (var review in Model.Review.Reviews)
        {
            <div class="item">
                <div class="ui avatar tiny image">
                    <img src="@images.GetProfileImageById(review.User.ProfileImageId, 100, 100)">
                </div>
                <div class="content">
                    <div class="header">
                        <a asp-action="Index" asp-controller="Profile" asp-route-id="@review.UserId">@review.User.Firstname</a>
                    </div>
                    <div class="keep-formatting">@review.ReviewMessage</div>
                </div>
            </div>
        }
    </div>
}


<h2 class="ui header">
    <i class="map marker alternate icon"></i>
    <div class="content">
        Map
    </div>
</h2>

<div style="width:100%;height:300px" class="ui segment" id="js-googleMap">

</div>



@section Scripts{
    <script>
        $(document).ready(function () {

            $(".owl-carousel").owlCarousel({
                loop: true,
                items: 1,
                nav: true,
                dots: true
            });

            CalendarController.initialize(".js-calendar");
            GoogleMapsController.addMapWithMarker("js-googleMap",@Model.Latitude,@Model.Longitude, 15)
            $('.rating').rating('disable', {
                    maxRating: 5
                });
        });
    </script>
}